Repository ImJustLucas/RiiWARD, pull requests merged in 2023-12, with the labels that each got.

#2 Lucas h sign in
  __tests__/Auth/signin.test.tsx
  src/hooks/Auth.ts
Labels: good first issue

#4 [ADD] Test Add Project
  __tests__/Project/addProject.test.tsx
  src/hooks/tests/Project.ts
Labels: good first issue

#7 [ADD] Tests edit project
  __tests__/Project/editProject.test.tsx
  src/hooks/tests/Project.ts
Labels: good first issue

#19 Feature - Parcours d'ajout d'un projet
  src/components/Button.tsx
  src/components/Common/Buttons/LeftButton.tsx
  src/components/Common/Buttons/RightButton.tsx
  src/components/Icon.tsx
  src/components/StepBackground.tsx
  src/layouts/AppLayout.tsx
  src/pages/project/add-project.tsx
  src/screens/Project/AddCategoryProject.tsx
  src/screens/Project/AddCoverProject.tsx
  src/screens/Project/AddNameProject.tsx
  src/themes/light/index.ts
  src/types/project/project.ts
Labels: good first issue

#21 Add supabase et auth
  .gitignore
  middleware.ts
  next.config.js
  package.json
  pnpm-lock.yaml
  src/components/RequireAuth.tsx
  src/contexts/AuthContext.tsx
  src/hooks/useIsLogged.ts
  src/layouts/AppLayout.tsx
  src/layouts/ProtectedPage.tsx
  src/pages/examples/protected-page.tsx
  src/pages/test-auth.tsx
  src/services/Supabase/index.ts
  src/services/api/Auth/index.ts
  src/services/api/Country/index.ts
  src/services/api/Users/index.ts
  src/services/api/index.ts
  src/types/database/index.ts
Labels: enhancement

#22 :rocket: Add Projects page and :bug: fix console error for position
  pnpm-lock.yaml
  src/assets/images/projectImage.png
  src/components/Common/Bars/UserBar.tsx
  src/components/Common/Containers/RoundedContainer.tsx
  src/screens/Homepage.tsx
  src/screens/Projectspage.tsx
  src/themes/dark/index.ts
Labels: bug, enhancement

#25 ✨ Integration of log in and sign in pages
  .gitignore
  package-lock.json
  src/layouts/AppLayout.tsx
  src/screens/Login.tsx
  src/screens/Signin.tsx
Labels: enhancement

#26 Ajout de la page profil
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_19_12_2023_13_52_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_19_12_2023_13_52_[Changes]1/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_19_12_2023_13_52__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_19_12_2023_13_52__Changes_1.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/components/Header/Index.tsx
  src/hooks/tests/Profile.ts
  src/pages/profile.tsx
  src/screens/.Profil.tsx.swp
  src/screens/Profil.tsx
Labels: good first issue

#34 :sparkles: link log in to supabase
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/screens/.Profil.tsx.swp
  src/screens/Login.tsx
  src/screens/Signin.tsx
  src/screens/SigninScreen.tsx
  src/screens/SignupScreen.tsx
  src/utils/ValidateEmail.ts
Labels: enhancement

#38 📝 create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#39 📝 create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#40 📝create LICENSE
  LICENSE
Labels: documentation

#41 📝 create SECURITY.md
  SECURITY.md
Labels: documentation

#42 📝 update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#35 Ajout d'un projet à la BDD
  src/components/Common/Buttons/LeftButton.tsx
  src/components/Common/Buttons/RightButton.tsx
  src/pages/project/add-project.tsx
  src/screens/Profil.tsx
  src/screens/Project/AddCategoryProject.tsx
  src/screens/Project/AddCoverProject.tsx
  src/screens/Project/AddNameProject.tsx
  src/screens/Projectspage.tsx
  src/services/api/Project/index.ts
  src/types/project/project.ts
Labels: Dynamic data

#33 :sparkles: Add get projects function and call
  next.config.js
  package.json
  src/assets/images/avatar.png
  src/assets/images/homeAvatar.jpg
  src/components/Common/Bars/UserBar.tsx
  src/pages/projects.tsx
  src/screens/Homepage.tsx
  src/screens/Projectspage.tsx
  src/services/api/Projects/index.ts
  src/services/api/Users/index.ts
  src/services/api/index.ts
  src/types/database/index.ts
Labels: Dynamic data

#43 ✨ feat/add community standards
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  SECURITY.md
  pull_request_template.md
Labels: documentation

#53 :globe_with_meridians: Update all texts in english and add link signup
  src/components/Header/Index.tsx
  src/pages/index.tsx
  src/screens/Profil.tsx
  src/screens/Projectspage.tsx
  src/screens/SigninScreen.tsx
Labels: enhancement, refactor

#55 ♻️ refact auth context with set methods
  src/components/Header/Index.tsx
  src/contexts/AuthContext.tsx
  src/screens/SigninScreen.tsx
Labels: refactor

#54 Refactor/code architecure
  src/components/Common/BackDrop/Backdrop.tsx
  src/components/Header/ContainerText.tsx
  src/pages/projects.tsx
  src/pages/test-auth.tsx
  src/screens/Homepage.tsx
  src/screens/Profil.tsx
  src/screens/Projectspage.tsx
  src/services/api/Country/index.ts
  src/services/api/Project/index.ts
  src/services/api/Projects/index.ts
  src/services/api/index.ts
Labels: refactor

#57 [FIX] Comments PR
  CONTRIBUTING.md
  src/hooks/tests/Profile.ts
  src/themes/light/index.ts
Labels: bug
