Repository ImJustLucas/RiiWARD, pull requests merged in 2024-02, with the labels that each got.

#36 Issue #28: Loading and 401
  package-lock.json
  src/components/Loading.tsx
  src/pages/401.tsx
Labels: enhancement

#64 :memo: DOCS add sections and enhance README (#062)
  README.md
  assets/riiward-diagram.png
  assets/riiward-logo.png
  assets/riiward.png
Labels: refactor

#71 59-mise à jour du style
  src/pages/_app.tsx
  src/screens/SigninScreen.tsx
  src/screens/SignupScreen.tsx
  src/themes/light/index.ts
  src/types/themes/index.ts
Labels: refactor

#70 Refacto/63 page profil
  src/components/CardProjects/CardProject.tsx
  src/components/Common/Links/SeeAllLink.tsx
  src/components/Common/Tags/SkillsTag.tsx
  src/screens/Profil.tsx
  src/themes/light/index.ts
  src/types/themes/index.ts
Labels: Dynamic data, refactor

#72 Feat/one project page
  .gitignore
  package-lock.json
  src/components/Common/Avatar.tsx
  src/components/Common/Buttons/LikeButton.tsx
  src/components/Common/SocialBar.tsx
  src/components/Pages/OneProject/GridCells/LikeBtnCell.tsx
  src/components/Pages/OneProject/GridCells/ProjectAdvencement.tsx
  src/components/Pages/OneProject/GridCells/ProjectContributors.tsx
  src/components/Pages/OneProject/GridCells/ProjectDescription.tsx
  src/components/Pages/OneProject/GridCells/ProjectHiring.tsx
  src/components/Pages/OneProject/GridCells/ProjectName.tsx
  src/components/Pages/OneProject/GridCells/ProjectPreview.tsx
  src/components/Pages/OneProject/GridCells/ProjectScore.tsx
  src/components/Pages/OneProject/GridCells/ProjectSkills.tsx
  src/components/Pages/OneProject/GridCells/index.ts
  src/pages/404.tsx
  src/pages/project/[id].tsx
  src/screens/Project/SingleProjectScreen.tsx
  src/styles/components/Container/index.ts
  src/themes/light/index.ts
  src/types/project/project.ts
Labels: Dynamic data

#76 ♻️ refacto header
  src/components/Header/Index.tsx
  src/pages/index.tsx
  src/pages/users/me.tsx
Labels: refactor

#79 🌐 ADD Traduction FR
  src/components/Header/Index.tsx
  src/pages/add-project.tsx
  src/screens/Profil.tsx
  src/screens/Project/Step1.tsx
  src/screens/Project/Step2.tsx
  src/screens/Project/Step3.tsx
  src/screens/Project/Step4.tsx
  src/screens/Project/Step5.tsx
  src/screens/Project/Step6.tsx
  src/screens/Projectspage.tsx
  src/screens/SigninScreen.tsx
  src/screens/SignupScreen.tsx
Labels: refactor

#83 ✨ ADD multi skills select
  src/screens/Project/Step3.tsx
  src/screens/Project/Step5.tsx
  src/services/api/Project/index.ts
  src/types/project/project.ts
Labels: enhancement, Dynamic data

#92 💄 Update form step 6 style
  src/screens/Project/Step6.tsx
Labels: Quick fix

#90 :sparkles: display all projects
  src/components/Common/Bars/UserBar.tsx
  src/screens/Projectspage.tsx
Labels: enhancement

#93 Global fixes + Ajout des skills dans la page profil utilisateur
  .eslintrc.json
  src/components/Header/Index.tsx
  src/screens/Profil.tsx
  src/screens/Projectspage.tsx
  src/services/api/Skills/index.ts
  src/types/skill/skill.ts
Labels: enhancement, refactor

#96 🐛 Redirection depuis page profil si user pas connecté
  src/screens/Profil.tsx
Labels: bug

#95 💄 Fix button projects page
  src/screens/Projectspage.tsx
Labels: Quick fix

#99 🔖 release v0.1.1
  package.json
Labels: release review

#100 🔖 release v0.1.2
  package.json
  src/components/Common/Containers/RoundedContainer.tsx
  src/screens/Project/Step2.tsx
  src/screens/Project/Step3.tsx
  src/screens/Project/Step4.tsx
  src/screens/Project/Step5.tsx
  src/screens/ProjectsSwiper.tsx
  src/services/api/Project/index.ts
  src/services/api/Skills/index.ts
  src/types/project/project.ts
Labels: release review

#102 💄 FIX Card text size
  src/screens/ProjectsSwiper.tsx
Labels: Quick fix

#103 🐛 Styles quand données vides
  src/components/CardProjects/CardProject.tsx
  src/components/Header/Index.tsx
  src/screens/Profil.tsx
Labels: bug

#104 🐛 Styles cards
  src/screens/Profil.tsx
Labels: bug
